version: "24.0"  # Adjust version if needed

services:
  frontend:
    build: 
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "8080:80"
  backend:
    build: 
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "3000:3000"
