version: "3.9"  # This is the latest docker compose version, the last legacy version is 3.8, so defining 3.9 means we don't support legacy versions

services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile.fe.dev # This is the naming convention for a dockerfile
    ports:
      - "3000:3000" # This is port forwarding, that means that port 3000 on the container will be forwarded to port 8080 on the host machine
    volumes:
      - ./frontend:/app # This is a volume, it means that the current directory will be mounted to /app in the container, so any changes in the current directory will be reflected in the container
      - /app/node_modules/

  backend:
    build: 
      context: .
      dockerfile: Dockerfile.be.dev # Same as above
    ports:
      - "8080:8080" # Remember "Host:Container"
    volumes:
      - ./backend:/app
      - ./config/dev:/app/config
      - /app/tmp/
