version: '3.9'

services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile.fe.prod
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    ports:
      - "8080:80"

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile.be.prod
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped