root = "."
tmp_dir = "tmp"

[build]
    cmd = "go build -o ./tmp/main ."
    bin = "tmp/main"
    include_ext = ["go", "mod", "sum"]
    exclude_dir = ["tmp", "config"]
    log = "air.log"
    poll = true
    stop_on_error = true
    rerun = true
    rerun_delay = 500

[log]
    time = true
    main_only = false

[color]
    main = "magenta"
    watcher = "cyan"
    build = "yellow"
    runner = "green"

[misc]
clean_on_exit = true